# Generated by Django 3.2.15 on 2022-09-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusOneGuest',
            fields=[
                ('guest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='home.guest')),
                ('invited_guest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='plus_one_guest', serialize=False, to='home.guest')),
            ],
            bases=('home.guest',),
        ),
    ]
